schedules:
- cron: "30 22 * * 2"
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng

parameters:
  - name: pools
    type: object
    default:
      - type: linux
        name: 1es-pool-azfunc
        image: 1es-ubuntu-22.04
        os: linux
      - type: windows
        name: 1es-pool-azfunc
        image: 1es-windows-2022
        os: windows 
      - type: macos
        name: Azure Pipelines
        image: macOS-latest
        os: macOS

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Build_And_Test

      jobs:
      - template: /eng/ci/templates/jobs/build-and-test.yml@self
        parameters:
          pools: ${{ parameters.pools }}