schedules:
- cron: "30 22 * * 2"
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
  - name: pools
    type: object
    default:
      - type: linux
        name: 1es-pool-azfunc-public
        image: 1es-ubuntu-22.04
        os: linux
      - type: windows
        name: 1es-pool-azfunc-public
        image: 1es-windows-2022
        os: windows 
      - type: macos
        name: Azure Pipelines
        image: macOS-latest
        os: macOS

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true

    stages:
    - stage: Build_And_Test

      jobs:
      - template: /eng/ci/templates/jobs/build-and-test.yml@self
        parameters:
            pools: ${{ parameters.pools }}